version: "3.9"
services:
  go-server:
    container_name: go-server
    build:
      dockerfile: ./iac/docker/Dockerfile
      context: ../..
    volumes:
    - .:/go/src/go-fiber/
    env_file:
      - ../../.env
    ports:
    - "9000:3000"
    depends_on:
      - postgres

  postgres:
    container_name: go-db
    image: postgres:13-alpine
    volumes:
      - ${HOME}/go-server-postgres/data/:/var/lib/postgresql/data
    
    env_file:
      - ../../.env

    ports:
      - 5432:5432
